---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: aws-test
  namespace: default
  annotations:    # here with the Annotations we are saying that this serviceaccount we are allowing EKS Amazon and the Role this serviceaccount is  going to use is the role we created --
    eks.amazonaws.com/role-arn:  arn:aws:iam::457668643577:role/test-oidc      #usig my account iD       # arn:aws:iam::411854276167:role/test-oidc   # in test-oidc 
---
apiVersion: v1
kind: Pod
metadata:
  name: aws-cli
  namespace: default
spec:
  serviceAccountName: aws-test
  containers:
    - name: aws-cli
      image: amazon/aws-cli
      command: [ "/bin/bash", "-c", "--" ]
      args: [ "while true; do sleep 30; done;" ]
  tolerations:
    - operator: Exists
      effect: NoSchedule
